### ISSUE TITLE
Prevent line breaks in code blocks

### ISSUE THREAD

**Issue by nasourso** [xy2z/PineDocs#85]
It would be great to have the option to prevent line breaks in code blocks. The user should be able to horizontally scroll in individual code blocks.

**Comment by xy2z** [comment]
Good point, actually i think this should be the default.

Feel free to submit a PR or I might look at this later this month

**Comment by xy2z** [comment]
This is now fixed in release v1.1.1

**Comment by nasourso** [comment]
Thank you for your fast push! Scrolling vertically works but it seems something else is now broken: When I create a code block with multiple lines everything gets pushed into one line.

A code block that should look like that:
Line 1
Line 2
Line 3

Looks like:
Line 1 Line 2 Line 3


And there is another problem: When I put 2 or more empty lines into a code block it does not get recognized as a code block.

**Comment by xy2z** [comment]
This should work now, can you test it @nasourso ?
If you use docker, use the "latest" tag

**Comment by nasourso** [comment]
The unwanted line breaks are gone. Good job!
I found out why my code block broke after I put empty lines into it.

My file looks like that:
![e1](https://user-images.githubusercontent.com/8536119/78673486-7fc85980-78e2-11ea-9bb2-1d696b7f2edd.PNG)

This is what it looks like in PineDocs:
![e2](https://user-images.githubusercontent.com/8536119/78673666-c027d780-78e2-11ea-8eee-608de8ec3cd2.PNG)


When I put a new line between the - 2 and the beginning of the code block it outputs it correctly.

I do not know if this is a markdown thing or a bug in PineDocs.

**Comment by xy2z** [comment]
great!
the other issues sounds weird, i can see it works here in github so it should work in markdown.
it's using an old version of "marked" so i'll try to update it and see maybe that will help.
but thats a new issue: #86

**Comment by xy2z** [comment]
hey @nasourso this should work now in v1.1.3

**Comment by nasourso** [comment]
Sadly it still does not work with my example file. It now looks like that:

![e3](https://user-images.githubusercontent.com/8536119/79465172-48049480-7ffb-11ea-8390-cbdfae69b881.PNG)

**Comment by xy2z** [comment]
oh that sucks, but you have to make an issue over at markedjs github repo: https://github.com/markedjs/marked
